dsn_driver: {IBM DB2 ODBC DRIVER}
dsn_database: bludb
dsn_hostname: 2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud
dsn_port: 30756
dsn_protocol: TCPIP
dsn_security: SSL